### ISSUE TITLE
Author section not aligned in PR card

### ISSUE THREAD

**Issue by jveillet** [jveillet/tentacles-dashboard#155]
The authors information are not aligned with the rest of the card body for Pull Requests on the dashboard.

## Screenshot
<img width="406" alt="image" src="https://user-images.githubusercontent.com/5037407/69063918-9ba78d80-0a1d-11ea-9428-27e99231fafa.png">

**Comment by luchiago** [comment]
Hi, can I try this one?

**Comment by jveillet** [comment]
Hi @luchiago , thanks for considering to contribute! Sure, yes, go ahead  🙂 If you need more information, you can add a comment here (There might be some delays in my responses, so don't be mad if I don't reply right off the bat).
